{{- if not (and (hasKey .Values "verticalAutoscaling") (hasKey .Values.verticalAutoscaling "create") (eq .Values.verticalAutoscaling.create true)) }}
{{- if .Values.containers -}}
{{ $appName := include "app.fullname" . }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
