{{- $appName := include "app.fullname" . -}}
{{- $appNamespace := .Release.Namespace }}
{{- $appLabels := include "app.labels" . }}
{{- range .Values.persistentVolumeClaim -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $appName }}-{{ .name }}"
  namespace: {{ $appNamespace | quote }}
  labels:
    {{- $appLabels | nindent 4 }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
