{{- $appName := include "app.fullname" . }}
{{- $appNamespace := .Release.Namespace }}
{{- $appLabels := include "app.labels" . }}
{{- range .Values.imagePullSealedSecrets}}
{{- if .data }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
{{- if .fullName }}
  name: "{{ .fullName }}"
{{- else }}
  name: "{{ $appName }}-{{ .name }}"
{{- end }}
  namespace: {{ $appNamespace | quote }}
  labels:
    {{- $appLabels | nindent 4 }}
spec:
  encryptedData:
    {{- .data | nindent 4 }}
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      labels:
        {{- $appLabels | nindent 8 }}
{{- end }}
{{- end }}


