{{- $appName := include "app.fullname" . }}
{{- $appNamespace := .Release.Namespace }}
{{- $appLabels := include "app.labels" . }}
{{- range .Values.tlsSecrets }}
{{- if and .base64Certificate .base64PrivateKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $appName }}-tls-{{ .name }}"
  namespace: {{ $appNamespace | quote }}
  labels:
    {{- $appLabels | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: "{{ .base64Certificate }}"
  tls.key: "{{ .base64PrivateKey }}"
{{- end }}
{{- end -}}
