{{- $appName := include "app.fullname" . }}
{{- $appNamespace := .Release.Namespace }}
{{- $appLabels := include "app.labels" . }}
{{- range .Values.secrets }}
{{- if .data }}
---
apiVersion: v1
kind: Secret
metadata:
{{- if .fullName }}
  name: "{{ .fullName }}"
{{- else }}
  name: "{{ $appName }}-{{ .name }}"
{{- end }}
  namespace: {{ $appNamespace | quote }}
  labels:
    {{- $appLabels | nindent 4 }}
type: Opaque
data:
  {{- .data | nindent 2 }}
{{- end }}
{{- end -}}
